#!/bin/sh
# alias get='sudo pacman -S'
alias up='sudo pacman -Syyu'
alias update='sudo pacman -Syyu'
alias y='yay -Sua'
alias pacbat='pacman -Qe | bat'
alias sbu="sudo pacman -Rns"
alias databases="sudo pacman -Syy"
alias pacup='kitty +kitten icat  && sudo pacman -Syu'

alias em="/usr/bin/emacs -nw"
alias emacs="emacsclient -c -a 'emacs'"
alias doomsync="~/.emacs.d/bin/doom sync"
alias doomdoctor="~/.emacs.d/bin/doom doctor"
alias doomupgrade="~/.emacs.d/bin/doom upgrade"
alias doompurge="~/.emacs.d/bin/doom purge"

alias ls="lsd"
# alias ls='exa -l --color=always --group-directories-first'  # long format
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias l='lsd --tree' # tree listing

alias highlight="highlight -O ansi --force"
alias hcat="cat | highlight"

alias v="nvim"

# alias fzf='fzf --color=16'
alias fzf-tmux='fzf-tmux --color=16'
alias splittedfzf='fzf-tmux -x --height ${FZF_TMUX_HEIGHT:-40%} -m --reverse --ansi'

alias npm="sudo npm"

alias luarocks="sudo luarocks"

alias benchmark='hyperfine'

alias open='xdg-open'

alias shutdown="systemctl poweroff"

alias xprocess="ps -eo pid,comm,%cpu --sort=-%cpu | head"
alias xmem="ps -eo pid,comm,%mem --sort=-%mem | head"
alias showport="ss -ltnp"
alias xtop='zfxtop'

alias dotar="tar -czvf"

alias trans='wid=$(xdotool selectwindow); picom-trans -w $wid'

alias .="c"
alias c..="c .."
alias cd..="c .."
alias ..="c .."

alias wallpapers='c ~/xos/wallpapers/static'

alias pipbat="pip list --format=columns | bat"
alias p="python3"

alias meteo="curl wttr.in"
alias xconfetty="ssh -p 2222 ssh.caarlos0.dev"
alias xfireworks="ssh -p 2223 ssh.caarlos0.dev"

alias icat="kitty +kitten icat"

alias enable-libv="sudo systemctl enable --now libvirtd"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
# ls="ls -hN --color=auto --group-directories-first" \
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	# g="git" \
	xcp="xclip -selection clipboard" \
	e="$EDITOR" \
	# f="$FILE" \


# alias \
# 	t="st &>/dev/null & disown" \
#     start="tbsm --quiet --theme riddler"

# Bare git dot config
alias \
	dots='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
	glfsforcerefs="git push origin --force 'refs/heads/*'"

#if [[ -f "$HOME/.local/bin/scripts/lfrun" ]]; then
#    alias lf="$HOME/.local/bin/scripts/lfrun"
#else
#    alias lf="/usr/bin/lfrun"
#fi
