#!/bin/sh



# alias zsh-theme-install="theme -i"








#🇵​​​​​🇦​​​​​🇨​​​​​🇲​​​​​🇦​​​​​🇳​​​​​

alias get='sudo pacman -S'
alias up='sudo pacman -Syyu'
alias y='yay -Sua'
alias pacbat='pacman -Qe | bat'
alias sbu="sudo pacman -Rns"
alias databases="sudo pacman -Syy"
alias pacup='kitty +kitten icat  && sudo pacman -Syu'


#🇪​​​​​🇲​​​​​🇦​​​​​🇨​​​​​🇸​​​​​

alias em="/usr/bin/emacs -nw"
alias emacs="emacsclient -c -a 'emacs'"
alias doomsync="~/.emacs.d/bin/doom sync"
alias doomdoctor="~/.emacs.d/bin/doom doctor"
alias doomupgrade="~/.emacs.d/bin/doom upgrade"
alias doompurge="~/.emacs.d/bin/doom purge"



alias open='xdg-open'

alias .="c"
alias glo="frogmouth"


#🇻​​​​​🇮​​​​​🇲​​​​​

# alias v="vim"



#NPM
alias npm="sudo npm"


alias luarocks="sudo luarocks"



#🇽​​​​​🇹​​​​​🇪​​​​​🇸​​​​​🇹​​​​​🇮​​​​​🇳​​​​​🇬​​​​​

alias xprocess="ps -eo pid,comm,%cpu --sort=-%cpu | head"
alias xmem="ps -eo pid,comm,%mem --sort=-%mem | head"
alias shutdown="systemctl poweroff"
alias paclog="sudo tail -f /var/log/pacman.log"
alias showport="ss -ltnp"
alias remind="notify-send "Reminder" "Time to take a break""

alias compress="tar -czvf"
alias extract="tar -xzvf"


alias invisible='picom-trans -w $(xdotool getactivewindow) 0'
alias trans='wid=$(xdotool selectwindow); picom-trans -w $wid'


alias modules='xos modules'
alias mate='c ~/Desktop/scuola/mate/'
alias scuola='c ~/Desktop/scuola/'
alias x='clear && xonsh'
alias xapps='c ~/Desktop/xapps/'
alias xapps='c ~/Desktop/xapps/'
alias todo='nvim ~/taskx'
alias xtop='zfxtop'




#🇨​​​​​🇦​​​​​🇷​​​​​🇬​​​​​🇴​​​​​

alias cr="cargo run"
alias ca="cargo add"
alias cs="cargo search"
#alias cl="cargo run -- --list"








#🇵​​​​​🇮​​​​​🇵​​​​

alias pipbat="pip list --format=columns | bat"
#alias ptest="python3"

#🇰​​​​​🇮​​​​​🇹​​​​​🇹​​​​​🇾​​​​​

alias d="kitty +kitten diff"

#🇸​​​​​🇸​​​​​🇭​​​​​

alias meteo="curl wttr.in"
alias xconfetty="ssh -p 2222 ssh.caarlos0.dev"
alias xfireworks="ssh -p 2223 ssh.caarlos0.dev"

#🇽​​​​​.🇪​​​​​🇳​​​​​🇦​​​​​🇧​​​​​🇱​​​​​🇪​​​​​
# Use neovim for vim if present.
#[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias xping="gping"
alias c..="c .."






alias centero= bash ~/.config/zsh/modules/center-output.sh
#alias zsh= zsh && c TODO








alias ..="c .."


alias gs="git status"
alias gc="git commit"
alias gp="git push"
alias gpl="git pull"
alias gpom="git push origin master"

# alias rmdir='rm -rf'






#🇩​​​​​🇪​​​​​🇫​​​​​🇦​​​​​🇺​​​​​🇱​​​​​🇹​​​​​

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
ls="ls -hN --color=auto --group-directories-first" \
alias \
	lt="colorls --tree" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	f="$FILE" \
	e="$EDITOR" \
	xcp="xclip -selection clipboard" \

# Changing "ls" to "exa"
# alias l='lsd' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
# alias ls='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias l='tree' # tree listing
# alias l.='exa -a | egrep "^\."'


alias \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
    vm="/usr/bin/vim" \
	wp="whatsapp-for-linux &>/dev/null & disown" \
	dc="discord &>/dev/null & disown" \
	tg="telegram-desktop &>/dev/null & disown"

alias \
	t="st &>/dev/null & disown" \
    start="tbsm --quiet --theme riddler"

# Bare git dot config
alias \
	dots='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
	glfsforcerefs="git push origin --force 'refs/heads/*'"

#if [[ -f "$HOME/.local/bin/scripts/lfrun" ]]; then
#    alias lf="$HOME/.local/bin/scripts/lfrun"
#else
#    alias lf="/usr/bin/lfrun"
#fi






alias icat="kitty +kitten icat"
alias s="kitty +kitten icat"





alias p="python3"
