#!/bin/sh

alias cp='cp -r'

alias get='sudo pacman -S'
alias up='sudo pacman -Syyu'
alias y='yay -Sua'
alias pacbat='pacman -Qe | bat'
alias sbu="sudo pacman -Rns"
alias databases="sudo pacman -Syy"
alias pacup='kitty +kitten icat  && sudo pacman -Syu'

alias em="/usr/bin/emacs -nw"
alias emacs="emacsclient -c -a 'emacs'"
alias doomsync="~/.emacs.d/bin/doom sync"
alias doomdoctor="~/.emacs.d/bin/doom doctor"
alias doomupgrade="~/.emacs.d/bin/doom upgrade"
alias doompurge="~/.emacs.d/bin/doom purge"

alias v="nvim"

alias npm="sudo npm"

alias luarocks="sudo luarocks"

alias benchmark='hyperfine'

alias open='xdg-open'

alias shutdown="systemctl poweroff"

alias xprocess="ps -eo pid,comm,%cpu --sort=-%cpu | head"
alias xmem="ps -eo pid,comm,%mem --sort=-%mem | head"
alias showport="ss -ltnp"
alias xtop='zfxtop'

alias dotar="tar -czvf"

alias trans='wid=$(xdotool selectwindow); picom-trans -w $wid'

alias .="c"
alias c..="c .."
alias cd..="c .."
alias ..="c .."


alias modules='xos modules'

alias wallpapers='c ~/xos/wallpapers/static'



alias mate='c ~/Desktop/scuola/mate/'
alias scuola='c ~/Desktop/scuola/'
alias xapps='c ~/Desktop/xapps/'

alias glo="frogmouth"

alias pipbat="pip list --format=columns | bat"
alias p="python3"

alias meteo="curl wttr.in"
alias xconfetty="ssh -p 2222 ssh.caarlos0.dev"
alias xfireworks="ssh -p 2223 ssh.caarlos0.dev"

alias icat="kitty +kitten icat"

alias gs="git status"
alias gc="git commit"
alias gp="git push"
alias gpl="git pull"
alias gpom="git push origin master"

alias ls="lsd -la"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
# ls="ls -hN --color=auto --group-directories-first" \
alias \
	lt="colorls --tree" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	xcp="xclip -selection clipboard" \
	# f="$FILE" \
	# e="$EDITOR" \

# Changing "ls" to "exa"
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
# alias ls='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias l='lt' # tree listing


alias \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
    vm="/usr/bin/vim" \
	wp="whatsapp-for-linux &>/dev/null & disown" \
	dc="discord &>/dev/null & disown" \
	tg="telegram-desktop &>/dev/null & disown"

# alias \
# 	t="st &>/dev/null & disown" \
#     start="tbsm --quiet --theme riddler"

# Bare git dot config
alias \
	dots='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
	glfsforcerefs="git push origin --force 'refs/heads/*'"

#if [[ -f "$HOME/.local/bin/scripts/lfrun" ]]; then
#    alias lf="$HOME/.local/bin/scripts/lfrun"
#else
#    alias lf="/usr/bin/lfrun"
#fi

alias fzf='fzf --color=16'
alias fzf-tmux='fzf-tmux --color=16'
