#!/usr/bin/env bash

encode_to_url_format() {
	echo "$1" | sed 's/ /%20/g'
}

check_if_empty() {
	[[ -z "$1" ]] && echo "0" || echo "$1"
}

KEY=56bfec39d45f284396f7e099cf4d150e
ID='3466537'
UNIT='metric'
CITY='Caxias do Sul'

WEATHER=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$KEY&id=$ID&units=$UNIT")

WEATHER_DESC=$(echo "$WEATHER" | jq -r ".weather[0].main")
WEATHER_TEMP=$(echo "$WEATHER" | jq ".main.temp" | cut -d "." -f 1)
WEATHER_ICON_CODE=$(echo "$WEATHER" | jq -r ".weather[].icon" | head -1)
WEATHER_FEELS_LIKE=$(echo "$WEATHER" | jq ".main.feels_like" | cut -d "." -f 1)
WEATHER_HUMIDITY=$(echo "$WEATHER" | jq ".main.humidity" | cut -d "." -f 1)
WEATHER_ICON=""
WEATHER_HEX=""

case $WEATHER_ICON_CODE in
"01d")
	WEATHER_ICON=""
	WEATHER_HEX="#c6a679"
	;;
"01n")
	WEATHER_ICON=""
	WEATHER_HEX="#9ec3c4"
	;;
"02d")
	WEATHER_ICON=""
	WEATHER_HEX="#ceb188"
	;;
"02n")
	WEATHER_ICON=""
	WEATHER_HEX="#adadff"
	;;
"03d")
	WEATHER_ICON=""
	WEATHER_HEX="#cacaca"
	;;
"03n")
	WEATHER_ICON=""
	WEATHER_HEX="#cacaca"
	;;
"04d")
	WEATHER_ICON=""
	WEATHER_HEX="#cacaca"
	;;
"04n")
	WEATHER_ICON=""
	WEATHER_HEX="#4c4c4c"
	;;
"09d")
	WEATHER_ICON=""
	WEATHER_HEX="#a39ec4"
	;;
"09n")
	WEATHER_ICON=""
	WEATHER_HEX="#a39ec4"
	;;
"10d")
	WEATHER_ICON=""
	WEATHER_HEX="#9ec3c4"
	;;
"10n")
	WEATHER_ICON=""
	WEATHER_HEX="#9ec3c4"
	;;
"11d")
	WEATHER_ICON=""
	WEATHER_HEX="#ceb188"
	;;
"11n")
	WEATHER_ICON=""
	WEATHER_HEX="#ceb188"
	;;
"13d")
	WEATHER_ICON=""
	WEATHER_HEX="#cacaca"
	;;
"13n")
	WEATHER_ICON=""
	WEATHER_HEX="#cacaca"
	;;
"40d")
	WEATHER_ICON=""
	WEATHER_HEX="#9ec3c4"
	;;
"40n")
	WEATHER_ICON=""
	WEATHER_HEX="#9ec3c4"
	;;
*)
	WEATHER_ICON=""
	WEATHER_HEX="#4c4c4c"
	;;
esac

case $1 in
"current_temp")
	check_if_empty "$WEATHER_TEMP"
	;;
"current_temp_fahrenheit")
	WEATHER_TEMP=$("$WEATHER_TEMP" 9 / 5 + 32)
	check_if_empty "$WEATHER_TEMP"
	;;
"feels_like")
	check_if_empty "$WEATHER_FEELS_LIKE"
	;;
"humidity")
	check_if_empty "$WEATHER_HUMIDITY"
	;;
"weather_desc")
	[[ -z $WEATHER_DESC ]] && echo "Not Available." || echo "$WEATHER_DESC"
	;;
"icon")
	echo $WEATHER_ICON
	;;
"hex")
	echo $WEATHER_HEX
	;;
"full")
	echo "$WEATHER"
	;;
"city")
	echo "$CITY"
	;;
"wmodule")
	echo $WEATHER_ICON "$WEATHER_TEMP"°
	;;
esac
